### ISSUE TITLE
Unable to retrieve Auth 2.0 token after login

### ISSUE THREAD

**Issue by faluciano** [armintum/MusicLM#4]
There seems to be an issue where you are unable to retrieve the token after a successful login.
```
Traceback (most recent call last):
  File "c:/Users/Felix/Documents/MusicLM/example.py", line 4, in <module>
    music = Music()
  File "c:\Users\Felix\Documents\MusicLM\MusicLM.py", line 29, in __init__
    self.token = self.get_token()
  File "c:\Users\Felix\Documents\MusicLM\MusicLM.py", line 123, in get_token
    raise Exception("Unable to obtain token")
Exception: Unable to obtain token
```

Not sure if there was a change in the way MusicLM does authentication

**Comment by plon** [comment]
I was not able to reproduce. Try using non headless chrome driver and see what happens.

**Comment by faluciano** [comment]
It seems like while login in 2fa is being asked for the account. Not using that seems to resolve the issue
